alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias md='mkdir -p'
alias rd='rmdir'

alias ls='ls -G'
alias ll='ls -l'
alias la='ls -la'
alias l='ls -lF'
alias l.='ls -d .*'
alias tree='tree -C'

alias grep='grep --color=auto'
alias f='find . -name'
alias which='command -v'

alias myip='curl -s https://ipinfo.io/ip; echo'
alias ping='ping -c 5'

alias reload='source ~/.zshrc'

alias pn='pnpm'
alias v='nvim'
alias vim='nvim'

alias ds-clean='find . -name .DS_Store -type f -delete 2>/dev/null; printf ".DS_Store files removed from current directory\n"'
alias ds-clean-home='find ~ -name .DS_Store -type f -delete 2>/dev/null; printf ".DS_Store files removed from home\n"'

alias gcl='git clone'
alias ginit='git init'
alias ga='git add'
alias gmv='git mv'
alias grs='git restore'
alias grm='git rm'
alias gbis='git bisect'
alias gd='git diff'
alias gg='git grep'
alias gl='git log'
alias gsh='git show'
alias gs='git status'
alias gb='git branch'
alias gc='git commit'
alias gm='git merge'
alias grb='git rebase'
alias gr='git reset'
alias gsw='git switch'
alias gt='git tag'
alias gf='git fetch'
alias gpl='git pull'
alias gps='git push'
